### ISSUE TITLE
Drop old rho remote jobs 

### ISSUE THREAD

**Issue by elyezer** [quipucords/ci#41]
We got our first green build for the current rho remote job yesterday and the second today so I think we are safe to drop the old remote jobs.

**Comment by elyezer** [comment]
@kdelee any objections?

**Comment by kdelee** [comment]
@elyezer Nope!

On Jan 24, 2018 10:43 AM, "Elyézer Rezende" <notifications@github.com>
wrote:

@kdelee <https://github.com/kdelee> any objections?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/quipucords/ci/issues/41#issuecomment-360176109>, or mute
the thread

**Comment by elyezer** [comment]
Old jobs deleted from Jenkins.
